default_stages: [commit]

repos:
  - repo: https://github.com/Trim21/pre-commit-hooks
    rev: c7a95cc4bd7861446be192a3b83c7a2ca1d6d910  # frozen: v0.2.3
    hooks:
      - id: yamlfmt
      - id: poetry-check-lock
      - id: find-trailing-comma

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 6e2418c5521b7d606e72914dced3253f9ace1205  # frozen: v3.4.0
    hooks:
      - id: check-case-conflict
      - id: check-ast
      - id: check-builtin-literals
      - id: check-byte-order-marker
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-added-large-files  # check for file bigger than 500kb
      - id: debug-statements
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        args: [--remove]

  - repo: https://github.com/timothycrosley/isort
    rev: a6222a8a125ec719724e628a5d3d0d5c60923281  # frozen: 5.8.0
    hooks:
      - id: isort

  - repo: https://github.com/asottile/pyupgrade
    rev: 24f855af7650827d000ca287b8fab133914ff6a3  # frozen: v2.14.0
    hooks:
      - id: pyupgrade
        args: [--py36-plus]

  - repo: https://github.com/myint/autoflake
    rev: 7a53fdafc82c33f446915b60fcac947c51279260  # frozen: v1.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
          - --expand-star-imports

  - repo: https://github.com/PyCQA/doc8.git
    rev: 1fc3c214b267d57188658c17b60cfed0752deb2f  # frozen: 0.9.0a1
    hooks:
      - id: doc8
        name: Check rst file
        args: [--max-line-length=88]
        files: \.rst$

  - repo: https://github.com/psf/black
    rev: 14c76e89716b5b53c97ece80bb935ea956b7dd89  # frozen: 21.5b0
    hooks:
      - id: black
