[tool.poetry]
name = "transmission-rpc"
version = "3.0.0a0"
description = "Python module that implements the Transmission bittorent client RPC protocol"
authors = ["Trim21 <i@trim21.me>"]
readme = 'README.md'
repository = 'https://github.com/Trim21/transmission-rpc'
license = 'MIT'
packages = [{ include = 'transmission_rpc' }]
classifiers = [
  'Intended Audience :: Developers',
  'Development Status :: 2 - Pre-Alpha',
  'License :: OSI Approved :: MIT License',
  'Topic :: Communications :: File Sharing',
  'Topic :: Internet',
  'Topic :: Software Development :: Version Control :: Git',
  'Programming Language :: Python :: 3.6',
  'Programming Language :: Python :: 3.7',
  'Programming Language :: Python :: 3.8',
]

[tool.poetry.dependencies]
python = "^3.6.1"
# dependencies
requests = "^2.23.0"
yarl = "^1.4.2"
# build cos
sphinx = { version = "^2.2", optional = true }
sphinx-rtd-theme = { version = "^0.4.3", optional = true }

[tool.poetry.extras]
docs = ['sphinx', 'sphinx-rtd-theme']

[tool.poetry.dev-dependencies]
# tests
pytest = "5.2.2"
pytest-mock = "1.11.2"
pytest-asyncio = "0.10.0"
pytest-faker = "2.0.0"
pytest-jest = "0.3.0"
pytest-rerunfailures = "7.0"
# linter and formatter
pre-commit = "2.3.0"
flake8-comprehensions = "3.0.1"
flake8-bugbear = "19.8.0"
flake8-mutable = "1.2.0"
doc8 = "0.8.0"
yapf = "^0.30.0"
pytest-cov = "^2.8.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
