version: '3'

dotenv:
  - .env

tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  lint:
    cmds:
      - poetry run ruff .
      - poetry run mypy --show-column-numbers transmission_rpc
      - poetry run pre-commit run --all-files

  test:
    cmds:
      - poetry run pytest

  build:docs:
    sources:
      - transmission_rpc/**/*.py
      - docs/**/*
      - exclude: docs/dist/**/*
    generates:
      - docs/dist/**/*
    cmds:
      - poetry run sphinx-build ./docs/ ./docs/dist/
