version: '3'

dotenv:
  - .env

tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  bump:
    vars:
      VERSION:
        sh: poetry version -s
    cmds:
      - git add pyproject.toml
      - 'git commit -m "bump: {{.VERSION}}"'
      - 'git tag "v{{.VERSION}}" -m "v{{.VERSION}}"'

  lint:
    cmds:
      - poetry run ruff .
      - poetry run mypy --show-column-numbers transmission_rpc
      - poetry run pre-commit run --all-files

  test:
    cmds:
      - poetry run pytest

  dev:docs:
    cmds:
      - poetry run sphinx-autobuild --fail-on-warning --watch transmission_rpc ./docs/ ./docs/dist/

  build:docs:
    cmds:
      - poetry run sphinx-build ./docs/ ./docs/dist/
