version: '3'

dotenv:
  - .env

tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  bump:
    vars:
      VERSION:
        sh: poetry version -s
    cmds:
      - git add pyproject.toml
      - 'git commit -m "bump: {{.VERSION}}"'
      - 'git tag "v{{.VERSION}}" -m "v{{.VERSION}}"'

  lint:
    cmds:
      - poetry run ruff .
      - poetry run mypy --show-column-numbers transmission_rpc
      - poetry run pre-commit run --all-files

  test:
    cmds:
      - poetry run pytest

  dev:docs:
    cmds:
      - poetry run sphinx-autobuild -W --watch transmission_rpc ./docs/ ./dist/

  build:docs:
    sources:
      - docs/**/*
      - transmission_rpc/**/*
    generates:
      - dist/**/*
    cmds:
      - rm -rf dist/
      - poetry run sphinx-build -W ./docs/ ./dist/
