"""Generate `transmission_rpc/_compat_table.py` from the transmission C++ sources.

Reads `libtransmission/quark.{h,cc}` and `libtransmission/api-compat.cc` from a
transmission checkout and produces the snake_case -> legacy (kebab/camelCase)
field name mapping used by the legacy RPC fallback path.

Usage:
    python3 scripts/generate_compat_table.py [path-to-transmission/libtransmission]

The generated file is committed; re-run this script when the transmission
sources change.
"""

from __future__ import annotations

import json
import re
import sys
from collections import defaultdict
from pathlib import Path

DEFAULT_TRANS = Path(__file__).resolve().parents[3] / "transmission/transmission/libtransmission"
OUT = Path(__file__).resolve().parent.parent / "transmission_rpc" / "_compat_table.py"

# header comment (excluding version markers, python file content is generated)
HEADER = '''\
"""AUTO-GENERATED by `scripts/generate_compat_table.py`. DO NOT EDIT.

snake_case (JSON-RPC 2.0) -> legacy (bespoke RPC) field-name mapping, extracted
from the transmission sources (libtransmission/api-compat.cc RpcKeys).
Method-specific exceptions are handled in `_compat.py`.
"""

'''


def parse_quark_names(text: str) -> list[str]:
    return re.findall(r"TR_KEY_(\w+)", text)


def parse_quark_values(text: str) -> list[str]:
    block = text.split("MyStatic", 1)[1]
    return re.findall(r'"([^"\\]*)"\s*sv', block)


def parse_pairs(text: str) -> list[tuple[str, str]]:
    rpc_keys = text.split("auto constexpr RpcKeys", 1)[1].split("auto constexpr SessionKeys", 1)[0]
    return re.findall(r"\.current\s*=\s*TR_KEY_(\w+),\s*\.legacy\s*=\s*TR_KEY_(\w+)", rpc_keys)


def main() -> int:
    trans_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(DEFAULT_TRANS)
    quark_h = (trans_dir / "quark.h").read_text()
    quark_cc = (trans_dir / "quark.cc").read_text()
    api_compat = (trans_dir / "api-compat.cc").read_text()

    names = parse_quark_names(quark_h)
    values = parse_quark_values(quark_cc)
    if len(names) != len(values):
        print(f"ERROR: quark name/value count mismatch: {len(names)} != {len(values)}", file=sys.stderr)
        return 1

    quark = dict(zip(names, values, strict=False))

    table: dict[str, list[str]] = defaultdict(list)
    for cur, legacy in parse_pairs(api_compat):
        cur_val = quark.get(cur)
        legacy_val = quark.get(legacy)
        if cur_val is None or legacy_val is None:
            print(f"WARN: unknown quark {cur!r} or {legacy!r}", file=sys.stderr)
            continue
        if legacy_val not in table[cur_val]:
            table[cur_val].append(legacy_val)

    lines = [HEADER, "SNAKE_TO_LEGACY: dict[str, tuple[str, ...]] = {"]
    for key in sorted(table):
        sorted_variants = sorted(table[key])
        if len(sorted_variants) == 1:
            variants = f"{json.dumps(sorted_variants[0])},"
        else:
            variants = ", ".join(json.dumps(v) for v in sorted_variants)
        lines.append(f"    {json.dumps(key)}: ({variants}),")
    lines.append("}")
    lines.append("")

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({len(table)} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
