name: lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  mypy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - uses: astral-sh/setup-uv@v10.2.0
        with:
          activate-environment: true
          enable-cache: true

      - uses: liskin/gh-problem-matcher-wrap@v4
        with:
          action: add
          linters: mypy

      - run: uv sync --frozen --extra dev

      - name: mypy
        run: mypy --show-column-numbers transmission_rpc

  pre-commit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        with:
          python-version: "3.x"

      - uses: trim21/actions/prek@master

  sphinx:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - uses: astral-sh/setup-uv@v10.2.0
        with:
          activate-environment: true
          enable-cache: true

      - run: uv sync --frozen --extra dev

      - run: sphinx-build -W docs/ dist/

  pyright:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - uses: astral-sh/setup-uv@v10.2.0
        id: setup-uv
        with:
          activate-environment: true

      - run: uv sync --frozen --extra dev

      - uses: jakebailey/pyright-action@v3
        with:
          python-path: ${{ steps.setup-uv.outputs.venv }}/bin/python
