name: Check PR

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - converted_to_draft
      - ready_for_review

permissions:
  pull-requests: write
  statuses: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          wip: true
